### ISSUE TITLE
Add System Priorities

### ISSUE THREAD

**Issue by MgramTheDuck** [antixenoinitiative/thargoid.watch#2]
Add a section listing systems by priority.

**Comment by Eckee** [comment]
I suggest listing the sistems as;

|- Current target ߷ | status 𑗍 |
|  --- | --- |
| Because AXI shipyard etc. | Dropped 1 in the last 4 days |

| Others in prio order| status |
| --- | --- |
|- Prio 1 | status |
|- Prio 2 | status |
|- Prio 3 | status |
|- ... | status |

Could we add current target for now? Without waiting to implement the whole priority infrastructure? It will definitely be nice to show the current target distinctively considering how hard it is to clear systems now. 

I also applied to Mentorship cause I want to participate more actively in Incursion defence. Listing priorities and deciding on the current target. I have an experience from the previous wars and it looks like there isn't any staff actively monitoring the status.

**Comment by MgramTheDuck** [comment]
Implementation complete for now.
